log_level: INFO
model_dir: models
threshold_file: threshold_wfv_optuna_results.csv
data:
  output_dir: "output_default"
  features_filename: "features_main.json"
  trade_log_pattern: "trade_log_*.csv*"
  trade_log_file: "trade_log.csv"
  raw_m1_filename: "XAUUSD_M1.csv"
  parquet_dir: "data/parquet_cache"
cleaning:
  fill_method: "drop"
