name: CI

on:
  push:

    branches: [main]
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:

          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black
      - name: Lint
        run: flake8 .
      - name: Format
        run: black --check .
      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-fail-under=85
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

